//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAP_WAB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer
    {
        public int ID { get; set; }
        public string Famer_Name { get; set; }
        public string Famer_Address { get; set; }
        public Nullable<long> Farmer_Mobile { get; set; }
        public Nullable<int> Farmer_Salary { get; set; }
        public string Farmer_Details { get; set; }
    }
}
