//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAP_WAB2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class officeEntities2 : DbContext
    {
        public officeEntities2()
            : base("name=officeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SignUp> SignUps { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Farmer> Farmers { get; set; }

        public System.Data.Entity.DbSet<MAP_WAB2.Models.User> Users { get; set; }
    }
}
