//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAP_WAB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignUp
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<long> Mobile { get; set; }
        public Nullable<long> DOB { get; set; }
        public string Paasword { get; set; }
    }
}
